### ISSUE TITLE
CPU로 돌릴 시 RuntimeError

### ISSUE THREAD

**Issue by lee-jeongha** [seujung/KoGPT2-summarization#1]
안녕하세요. CPU에서 해당 모델 돌려보고 있습니다.

train.py 실행 부분을 다음과 같이 수정해보았는데요.
`!python train.py  --gradient_clip_val 1.0 --max_epochs 1 --default_root_dir logs  --batch_size 4 --num_workers 4 --max_len 1024`

다음과 같은 오류가 나왔습니다.
![image](https://user-images.githubusercontent.com/81732746/118490556-05ab0b00-b759-11eb-8245-ed4ef4761e56.png)

GPU없이 해당 모델을 돌릴 수 있는 방법이 있을까요?

**Comment by seujung** [comment]
안녕하세요. 해당 부분은  pytorch 부분 관련해서 에러가 나는 것 같은데요. 

혹시 실행 환경이 어떻게 되는지를 알 수 있을까요?

**Comment by seujung** [comment]
추가 요청 사항이 없어서 closed 처리 하도록 하겠습니다.
